FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli

COPY . .

RUN ng build SportReserve_WebClient

FROM nginx:alpine AS final

COPY --from=builder /app/dist/SportReserve_WebClient /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]