FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SportReserve_Races/*.csproj ./Races/SportReserve_Races/
COPY SportReserve_Races_Db/*.csproj ./Races/SportReserve_Races_Db/

COPY nupkg ./nupkg/

RUN dotnet restore ./Races/SportReserve_Races/SportReserve_Races.csproj \
    --source ./nupkg \
    --source https://api.nuget.org/v3/index.json

COPY SportReserve_Races ./Races/SportReserve_Races
COPY SportReserve_Races_Db ./Races/SportReserve_Races_Db

RUN dotnet publish ./Races/SportReserve_Races/SportReserve_Races.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish ./

ENTRYPOINT ["dotnet", "SportReserve_Races.dll"]