FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SportReserve_ApiGateway/*.csproj ./SportReserve_ApiGateway/

COPY NuGet.config ./
COPY nupkg ./nupkg/

RUN dotnet restore ./SportReserve_ApiGateway/SportReserve_ApiGateway.csproj \
    --source ./nupkg \
    --source https://api.nuget.org/v3/index.json

COPY SportReserve_ApiGateway ./SportReserve_ApiGateway

RUN dotnet publish ./SportReserve_ApiGateway/SportReserve_ApiGateway.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish ./

ENTRYPOINT ["dotnet", "SportReserve_ApiGateway.dll"]