FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SportReserve_Emails/*.csproj ./SportReserve_Emails/

COPY nupkg ./nupkg/

RUN dotnet restore ./SportReserve_Emails/SportReserve_Emails.csproj \
    --source ./nupkg \
    --source https://api.nuget.org/v3/index.json

COPY SportReserve_Emails ./SportReserve_Emails

RUN dotnet publish ./SportReserve_Emails/SportReserve_Emails.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish ./

ENTRYPOINT ["dotnet", "SportReserve_Emails.dll"]