name: Server_ApiGateway - Pipeline

on:
  push:
    branches: ["**"]
    paths:
      - 'Server/ApiGateway/SportReserve_ApiGateway/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'Server/ApiGateway/SportReserve_ApiGateway/**'

jobs:
  build:
    runs-on: windows-latest 
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SportReserve_ApiGateway.csproj
        working-directory: ./Server/ApiGateway/SportReserve_ApiGateway

      - name: Build
        run: dotnet build SportReserve_ApiGateway.csproj --no-restore
        working-directory: ./Server/ApiGateway/SportReserve_ApiGateway
